### PR TITLE
Exercism Slack Emoji

### PR DESCRIPTION
**Pull request by rpottsoh**
Emoji that I added to Exercism Slack.....

### CODE REVIEW

**Comment by rpottsoh** [comment]
It might be nice to encourage others to open PRs of their own in order to contribute emojis that they have installed on Slack.

**Comment by iHiD** [comment]
@rpottsoh Thanks :) 

Could you rename them to `v1.png` and `v1_to_v2.gif` pls and then I'll merge. Thanks :)

**Comment by rpottsoh** [comment]
Thiis is sure a fine how do you do.  `v1.png` is not upper cased on my local copy.  Only on github...  Not sure how to fix that file.  I will be committing the other file, renamed, shortly.

**Comment by rpottsoh** [comment]
Ok, I got it.

**Comment by iHiD** [comment]
Thank you :)

**Pull request merged**
