### PR TITLE
fixes-exercism/website-icons#89

### LINKED ISSUE #89: Icon for Pharo track looks wierd and different than original Pharo icon
Hi Exercism team! 
I'm not designer, but current Pharo track icon looks quite different than what can be seen on pharo-project.org. It looks it is somehow autogenerated (probably caused by limited time of original maintainers). I tried to resolve this using Incscape and tried to simplify (colors and shapes) original Pharo icon that would fit to Exercism website. I will create PR to paste updated SVG file. Please let me know, if new SVG can be used. 
Thanks in advance!
David

### PR DESCRIPTION
**Pull request by Bajger**
fixes #89

### CODE REVIEW

**Comment by Bajger** [comment]
@taiyab Hi! Any news on reviewing this? Thanks!

**Comment by Bajger** [comment]
@iHiD Hi Jeremy! Do you know, why icon is not visible on exercism.io web site? It needs to be somehow released first? Thanks for answer! This one: https://github.com/exercism/website-icons/blob/main/tracks/pharo-smalltalk.svg

**Comment by iHiD** [comment]
It is for me. Maybe you have the old one cached locally?

Screenshot 2021-12-03 at 12 36 00

**Comment by Bajger** [comment]
Interesting, I've reset browser cache in Safari and still seeing this:
image

When I right-click image and open in new tab, it has following link. Isn't it cached by SDN somehow?
https://dg8krxphbh767.cloudfront.net/tracks/pharo-smalltalk.svg

**Comment by iHiD** [comment]
That same link is the correct updated image for me :) @ErikSchierboom - What about you?

**Pull request merged**
