### PR TITLE
Add icons of key features for Ballerina track

### PR DESCRIPTION
**Pull request by praneesha**
Add icons of key features for the Ballerina track.

### CODE REVIEW

**Comment by kytrinyx** [comment]
@praneesha This shouldn't be necessary.

Have you read the documentation in the section "Key Features" of this page?
https://exercism.org/docs/building/tracks/config-json

You would need to add it here, using already-existing icons.
https://github.com/exercism/ballerina/blob/bd629ab9b51492c0869bfb998fc61a0bf3dfd6e3/config.json#L548

**Comment by praneesha** [comment]
@kytrinyx - Can't we add new images if we are unable to find a matching one in the already-existing icons list?

**Comment by kytrinyx** [comment]
If you want to do that, you would need to start a discussion on the forum as to why you think it is necessary. I would suggest that you write up a draft of the six key features that you want to put in the config file, and include that in the forum post for context.

**Comment by praneesha** [comment]
Will consider that later.

@kytrinyx - Can you merge [this PR](https://github.com/exercism/ballerina/pull/226) to use the existing images?

**Comment by kytrinyx** [comment]
I'm not on the ballerina team. Are you in a hurry? Is there some context here that I'm missing?

**Comment by praneesha** [comment]
Will get it merged. No worries at all. Thanks a lot.

**Comment by ErikSchierboom** [comment]
> Can't we add new images if we are unable to find a matching one in the already-existing icons list?

This is not supported. In general, anything not track-specific is not open for contributions. We'd also prefer for changes like this to be discussed in the forums first.

**Review by LakshanWeerasinghe — COMMENTED** [review]
Format of the files are incorrect. Please upload them in `.svg` format.

**Comment by ErikSchierboom** [comment]
@LakshanWeerasinghe That's not the issue, the issue is that we don't take community contributions for icons.

**Comment by praneesha** [comment]
This is resolved via [this PR](https://github.com/exercism/ballerina/pull/226#pullrequestreview-1429130335).

Thanks a lot.

**Pull request closed without merging**
