### PR TITLE
add suggestion for ABAP track

### LINKED ISSUE #93: Add icon for ABAP track
Hi,
Add icon for ABAP track: https://github.com/exercism/abap

For ABAP there are no official or unofficial logos. I suggest making a logo that just says "ABAP", in some shade of blue.

### PR DESCRIPTION
**Pull request by larshp**
This is a suggestion for #93

closes #93

### CODE REVIEW

**Comment by larshp** [comment]
any thoughts, someone?

**Comment by iHiD** [comment]
@taiyab One for you to look at pls :)

**Comment by larshp** [comment]
@taiyab any thoughts?

There is no real logo for ABAP, and we are very boring in the ABAP world 😁 So its a fit IMHO

**Comment by larshp** [comment]
@taiyab

**Comment by larshp** [comment]
@taiyab

**Comment by larshp** [comment]
suggest just merging this PR, the icon can always be changed

**Comment by taiyab** [comment]
@larshp https://github.com/exercism/website-icons/pull/101

**Comment by larshp** [comment]
thanks, I'll close this PR 👍

**Pull request closed without merging**
